version: '3'

services:
  blogdocker:
    image: blogdocker
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - 5005:5005
  db:
    image: 'postgres:14.2-alpine'
    restart: always
    environment:
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
        - 5432:5432

volumes:
  db-data:
    driver: local
